Repository openshift/ironic-inspector-image, pull requests merged in 2019-07, with the labels that each got.

#2 Add Dockerfile.ocp
  Dockerfile.ocp
Labels: size/M

#4 Adding OWNERS file
  OWNERS
Labels: size/S

#3 Build container from rhel7
  Dockerfile.ocp
Labels: size/XS

#5 Merge ironic-inspector-image changes from upstream
  Dockerfile
  runironic-inspector.sh
Labels: lgtm, size/XS

#6 Merge latest changes from upstream
  Dockerfile
Labels: size/XS

#7 Update Dockerfile.ocp for Ironic Stein
  Dockerfile
  Dockerfile.ocp
Labels: size/XS

#8 apply latest changes from upstream
  Dockerfile
  inspector.conf
  runironic-inspector.sh
Labels: approved, lgtm, size/M

#9 Use config file in dockerfile.ocp
  Dockerfile.ocp
Labels: approved, lgtm, size/S

#10 backport to 4.2
  Dockerfile.ocp
Labels: approved, size/S
